### ISSUE TITLE
Can this remotely wake up a computer through a usb connection

### ISSUE THREAD

**Issue by crotoc** [Flowm/etherkey#3]
I have a gaming laptop but not supporting wake on lan or wireless lan. It can be waked through keyboard or mouse through clicking. Does this project help in this situation. If you have better solutions please le me know as well. Thanks!

**Comment by nummer30** [comment]
This isn't what we intended with our project, but I think it could work. If you plug in a regular USB keyboard and can wake up your Laptop using the USB keyboard (*not* the built-in keyboard), it should also work with Etherkey.

You will need another system that's always running (usually a Raspberry Pi) and is connected to the Teensy.

**Comment by crotoc** [comment]
Thanks! I searched more and found a solution like yours: https://randomnerdtutorials.com/raspberry-pi-zero-usb-keyboard-hid/. Hope it work! Appreciate for your confirmation!
