### ISSUE TITLE
With modification, can this control two computers?

### ISSUE THREAD

**Issue by seonwoolee** [Flowm/etherkey#5]
I'm interested in sending the exact same keystrokes to multiple computers at once. With some modification, would Etherkey be able to do this? I think it'd involve connecting a second Teensy to some other Raspberry Pi pins and transmitting the same signals to both Teensies.

If so, what part of the code should I modify?

**Comment by nummer30** [comment]
Hello @seonwoolee 

In theory, with multiple Teensys, it should be possible, yes. You will have to connect each Teensy to a different serial interface, and your "client" program needs to send the same data to all the serial interfaces at the same time.

For example, if you use `client/teensy-usb.py`, you would need to modify that to use multiple serial interfaces.
