### ISSUE TITLE
Teensy 4

### ISSUE THREAD

**Issue by ideologysec** [Flowm/etherkey#6]
Will this work with any of the Teensy 4 series? I'm brand new to the Arduino world, so I don't know enough to find out the answer to this myself yet.

The current note on the linked PJRC page says this: "Chips for Teensy 3.2 have been delayed until March 2023. Earlier this year we were told "gradual improvement in Q2" and limited supply in Q3 with most chips arriving by Q4. Now NXP has delayed the first chips until March 2023, and the rest until June 2023. PJRC is planning to resume production of Teensy 3.2 when these chips arrive, but if possible, we suggest switching to Teensy 4.0 or Teensy 4.1 for new projects. The IMXRT chip on Teensy 4 is less impacted by the global chip shortage. "

It would be great to be able to use this on a chip that's a little more widely available, since I'd like to get started on a project before June of next year... 😅

**Comment by nummer30** [comment]
Hi @ideologysec 

my tests found no issues with Etherkey on the Teensy 4.1. So I would assume you should be able to use a Teensy 4 or 4.1.

I hope that helps.
