### ISSUE TITLE
Add Support for function Keys

### ISSUE THREAD

**Issue by Davidthemastercoder** [Flowm/etherkey#7]
Hello first of all thanks for sharing with us this great thing.

Could you please add Support for Fuction Keys ? 
Like F1 - F12 so one could open the BIOS for example when the system is booting up ?

**Comment by nummer30** [comment]
Hello @Davidthemastercoder,

Thank your for your suggestion: support for F-Keys sounds like a great idea.

I don't see why this shouldn't be implemented in _Command Mode_.

However, in _Interactive Mode_, I fear this might be difficult. I'm not too sure about the details anymore (we implemented this stuff in 2014), but F-Keys in Terminal emulators are already complicated, and sending them over the serial interface to the teensy is difficult. (It would probably lead to restrictions which terminal and client has to be used)

Would it be sufficient for your use case if you could send the F-Keys in _Command Mode_ with the command `Send {F12}`?

**Comment by Davidthemastercoder** [comment]
Thank you very much, for that fast reply.
I would need to be able to use like a Script who can send those keystrokes. 
I mean i can use Python and the serial Module to Access the Teensy. 
And then i might be able to send keystrokes to switch the Mode. So it should work.

It would be very nice, if  you could implement it in the Command mode.
I try it than probably out and give you Feedback.

**Comment by nummer30** [comment]
Hi @Davidthemastercoder,

I just implemented support for F1-F12 in command mode in e2cba383fed8423d9d42a4f87fd7d58645db4ca5.
You can now do something like `Send !{F4}` to press Alt+F4, and similar things.

Please let me know if this works for you.

**Comment by Davidthemastercoder** [comment]
Thank you very much
